name: Release Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js (with Yarn)
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build Electron app
        run: yarn build

      - name: Get Version
        id: get_version
        run: |
          $VERSION = (Get-Content package.json | ConvertFrom-Json).version
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV
          echo "Version is $VERSION"

      - name: Create or Use Existing Tag
        id: tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if tag exists
          $tagExists = git ls-remote --tags origin "refs/tags/v$env:VERSION"
          
          if ($tagExists) {
            echo "Tag v$env:VERSION already exists. Using existing tag."
          } else {
            git tag "v$env:VERSION"
            git push origin "v$env:VERSION"
            echo "Created new tag v$env:VERSION"
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build release artifacts
        run: yarn electron-builder --win

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/**/*.exe
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
          body: |
            Release version ${{ env.VERSION }}
            
            ## What's Changed
            * Automated release from GitHub Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}