name: Release Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (with Yarn)
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build Electron app
        run: yarn build

      - name: Create a Git tag
        id: create_tag
        run: |
          $VERSION = (Get-Content package.json | ConvertFrom-Json).version
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v$VERSION"
          git push https://github-actions:${{ secrets.TOKEN }}@github.com/KhaledSaeed18/NoteMark.git "v$VERSION"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/**/*

      - name: Upload release to GitHub
        run: yarn electron-builder --win
